# Generated by Django 5.2.7 on 2025-12-06 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agent", "0001_initial"),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="cases.case",
            ),
        ),
    ]
