# Generated by Django 5.2.7 on 2025-11-04 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("document_access", "Document Access"),
                            ("document_delete", "Document Delete"),
                            ("data_export", "Data Export"),
                            ("data_delete", "Data Delete"),
                            ("settings_change", "Settings Change"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(blank=True, max_length=50)),
                ("resource_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action", "created_at"],
                        name="analytics_a_user_id_e0960a_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_a_created_9cacd0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("document_uploaded", "Document Uploaded"),
                            ("document_analyzed", "Document Analyzed"),
                            ("document_generated", "Document Generated"),
                            ("ai_query", "AI Query"),
                            ("conversation_started", "Conversation Started"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField(default=1.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "usage metric",
                "verbose_name_plural": "usage metrics",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "metric_type", "created_at"],
                        name="analytics_u_user_id_fc150b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_u_created_a26b2a_idx"
                    ),
                ],
            },
        ),
    ]
