# Generated by Django 5.2.7 on 2025-12-06 14:50

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="analysis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("urgent", "Urgent")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "Started"),
                    ("in-progress", "In Progress"),
                    ("done", "Done"),
                ],
                default="started",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=documents.models.document_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pleading", "Pleading"),
                    ("opinion", "Opinion"),
                    ("contract", "Contract"),
                    ("ai_generated", "AI Generated"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="document",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
